### ISSUE TITLE
Unable to build: sim_irq_h_54_1 is not a valid Ident

### ISSUE THREAD

**Issue by kellpossible** [Patryk27/simavr-ffi#2]
I'm getting the following error on Ubuntu attempting to build this crate from source, or from crates.io:

```
thread 'main' panicked at '"enum_(unnamed_at__/vendor/simavr/simavr/sim/sim_irq_h_54_1)" is not a valid Ident'
```

**Comment by Patryk27** [comment]
That's a funky one! Could you run `clang --version`?

**Comment by Patryk27** [comment]
I've tried to replicate this on the newest Ubuntu and everything seems to be alright - if you encounter this issue again, feel free to re-open!

**Comment by kellpossible** [comment]
Thanks I will try again! I'm using 22.04 will try clang version check
